%YAML:1.0

# If the LoadFile doesn't exist, the system gives a message and creates a new Atlas from scratch
System.LoadAtlasFromFile: "back_mono_atlas"
# System.LoadAtlasFromFile: "back_mono_2_atlas"
# System.LoadAtlasFromFile: "back_RGBD_atlas"

# The store file is created from the current session. If a file with the same name exists it is deleted
# System.SaveAtlasToFile: "back_mono_atlas"
# System.SaveAtlasToFile: "back_mono_2_atlas"
# System.SaveAtlasToFile: "ba7ck_RGBD_atlas"

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 521.9332556052045
Camera1.fy: 521.9332556052045
Camera1.cx: 320.0
Camera1.cy: 240.0

# Distortion parameters
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0
Camera1.k3: 0.0

# Camera resolution
Camera.width: 640
Camera.height: 480

# Camera frames per second
Camera.fps: 10

# Color order of the images (0: BGR, 1: RGB)
Camera.RGB: 1
Camera.bf: 32.0

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 100.0
Stereo.b: 0.10

# Depth map values factor
RGBD.DepthMapFactor: 1.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 6000
ORBextractor.scaleFactor: 1.15
ORBextractor.nLevels: 10
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 3

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
